### ISSUE TITLE
get funding for this micro project

### ISSUE THREAD

**Issue by BlocksOnAChain** [localnet-farm/localnet-farm#1]
create an issue on devgrants

**Comment by jimpick** [comment]
I submitted a funding request here:

https://github.com/filecoin-project/devgrants/issues/1133

**Comment by BlocksOnAChain** [comment]
sounds good, I approved it. @jimpick 
Do we want us to move the repo under filecoin org, similar to what we have for wallaby - https://github.com/filecoin-project/testnet-wallaby or keep it separate?

**Comment by jimpick** [comment]
I'm open to moving it. I envision this repo being the core gitops setup that can be used by multiple clusters. I'm not sure yet if I want to structure it as a monorepo or use multiple repos for various components. Anything specific to a particular deployed instance should be in a separate repo, I think.

**Comment by jimpick** [comment]
The microgrant was approved. I'll close this when the tokens are received (approximately 30 days).

**Comment by BlocksOnAChain** [comment]
sounds good, will check about the payment execution with FF @jimpick
